pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'dannoruwaanush/bnpl-aspnet-api'  //dockerusername/image-name
        DOCKER_REGISTRY = 'docker.io'
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/Dannoruwa-Anush/backend_dot_net.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    bat """
                        docker build -t %DOCKER_IMAGE%:%IMAGE_TAG% .
                        docker tag %DOCKER_IMAGE%:%IMAGE_TAG% %DOCKER_IMAGE%:latest
                    """
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([
                    usernamePassword(credentialsId: 'dannoruwaanush-dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD'
                    )
                ]) {
                    bat """
                        echo %DOCKER_PASSWORD% | docker login -u %DOCKER_USERNAME% --password-stdin
                        docker push %DOCKER_IMAGE%:%IMAGE_TAG%
                        docker push %DOCKER_IMAGE%:latest
                    """
                }
            }
        }
    }

    post {
        always {
            bat 'docker system prune -f'
            bat 'docker logout'
        }
    }
}