// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251126131344_installment_snapshot_tbl_modified")]
    partial class installment_snapshot_tbl_modified
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.BNPL_Installment", b =>
                {
                    b.Property<int>("InstallmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InstallmentID"));

                    b.Property<decimal>("AmountPaid_AgainstBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountPaid_AgainstLateInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Bnpl_Installment_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Bnpl_PlanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InstallmentNo")
                        .HasColumnType("int");

                    b.Property<decimal>("Installment_BaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Installment_DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastLateInterestAppliedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("LateInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OverPaymentCarriedFromPreviousInstallment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RefundDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BINARY(8)");

                    b.Property<decimal>("TotalDueAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("InstallmentID");

                    b.HasIndex("Bnpl_PlanID", "InstallmentNo")
                        .IsUnique();

                    b.ToTable("BNPL_Installments");
                });

            modelBuilder.Entity("WebApplication1.Models.BNPL_PLAN", b =>
                {
                    b.Property<int>("Bnpl_PlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Bnpl_PlanID"));

                    b.Property<decimal>("Bnpl_AmountPerInstallment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bnpl_InitialPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Bnpl_NextDueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Bnpl_PlanTypeID")
                        .HasColumnType("int");

                    b.Property<int>("Bnpl_RemainingInstallmentCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Bnpl_StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Bnpl_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Bnpl_TotalInstallmentCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BINARY(8)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Bnpl_PlanID");

                    b.HasIndex("Bnpl_PlanTypeID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.ToTable("BNPL_PLANs");
                });

            modelBuilder.Entity("WebApplication1.Models.BNPL_PlanSettlementSummary", b =>
                {
                    b.Property<int>("SettlementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SettlementID"));

                    b.Property<int>("Bnpl_PlanID")
                        .HasColumnType("int");

                    b.Property<string>("Bnpl_PlanSettlementSummary_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentInstallmentNo")
                        .HasColumnType("int");

                    b.Property<bool>("IsLatest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<decimal>("NotYetDueCurrentInstallmentBaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Paid_AgainstNotYetDueCurrentInstallmentBaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Paid_AgainstTotalArrears")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Paid_AgainstTotalLateInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BINARY(8)");

                    b.Property<decimal>("Total_AvailableOverPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total_InstallmentBaseArrears")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total_LateInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total_PayableSettlement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SettlementID");

                    b.HasIndex("Bnpl_PlanID");

                    b.ToTable("BNPL_PlanSettlementSummaries");
                });

            modelBuilder.Entity("WebApplication1.Models.BNPL_PlanType", b =>
                {
                    b.Property<int>("Bnpl_PlanTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Bnpl_PlanTypeID"));

                    b.Property<string>("Bnpl_Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Bnpl_DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("Bnpl_PlanTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("LatePayInterestRatePerDay")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Bnpl_PlanTypeID");

                    b.HasIndex("Bnpl_PlanTypeName")
                        .IsUnique();

                    b.ToTable("BNPL_PlanTypes");
                });

            modelBuilder.Entity("WebApplication1.Models.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BrandID"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BrandID");

                    b.HasIndex("BrandName")
                        .IsUnique();

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("WebApplication1.Models.Cashflow", b =>
                {
                    b.Property<int>("CashflowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CashflowID"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CashflowDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CashflowRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CashflowStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RefundDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BINARY(8)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CashflowID");

                    b.HasIndex("CashflowRef")
                        .IsUnique();

                    b.HasIndex("OrderID");

                    b.ToTable("Cashflows");
                });

            modelBuilder.Entity("WebApplication1.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WebApplication1.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.HasIndex("PhoneNo")
                        .IsUnique();

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WebApplication1.Models.CustomerOrder", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<bool?>("CancellationApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CancellationRejectionReason")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("CancellationRequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderPaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PaymentCompletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BINARY(8)");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.ToTable("CustomerOrders");
                });

            modelBuilder.Entity("WebApplication1.Models.CustomerOrderElectronicItem", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("E_ItemID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BINARY(8)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("OrderID", "E_ItemID");

                    b.HasIndex("E_ItemID");

                    b.ToTable("CustomerOrderElectronicItems");
                });

            modelBuilder.Entity("WebApplication1.Models.ElectronicItem", b =>
                {
                    b.Property<int>("ElectronicItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ElectronicItemID"));

                    b.Property<int>("BrandID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ElectronicItemImage")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ElectronicItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QOH")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BINARY(8)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ElectronicItemID");

                    b.HasIndex("BrandID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ElectronicItemName")
                        .IsUnique();

                    b.ToTable("ElectronicItems");
                });

            modelBuilder.Entity("WebApplication1.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApplication1.Models.BNPL_Installment", b =>
                {
                    b.HasOne("WebApplication1.Models.BNPL_PLAN", "BNPL_PLAN")
                        .WithMany("BNPL_Installments")
                        .HasForeignKey("Bnpl_PlanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BNPL_PLAN");
                });

            modelBuilder.Entity("WebApplication1.Models.BNPL_PLAN", b =>
                {
                    b.HasOne("WebApplication1.Models.BNPL_PlanType", "BNPL_PlanType")
                        .WithMany("BNPL_PLANs")
                        .HasForeignKey("Bnpl_PlanTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.CustomerOrder", "CustomerOrder")
                        .WithOne("BNPL_PLAN")
                        .HasForeignKey("WebApplication1.Models.BNPL_PLAN", "OrderID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BNPL_PlanType");

                    b.Navigation("CustomerOrder");
                });

            modelBuilder.Entity("WebApplication1.Models.BNPL_PlanSettlementSummary", b =>
                {
                    b.HasOne("WebApplication1.Models.BNPL_PLAN", "BNPL_PLAN")
                        .WithMany("BNPL_PlanSettlementSummaries")
                        .HasForeignKey("Bnpl_PlanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BNPL_PLAN");
                });

            modelBuilder.Entity("WebApplication1.Models.Cashflow", b =>
                {
                    b.HasOne("WebApplication1.Models.CustomerOrder", "CustomerOrder")
                        .WithMany("Cashflows")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerOrder");
                });

            modelBuilder.Entity("WebApplication1.Models.Customer", b =>
                {
                    b.HasOne("WebApplication1.Models.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("WebApplication1.Models.Customer", "UserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Models.CustomerOrder", b =>
                {
                    b.HasOne("WebApplication1.Models.Customer", "Customer")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WebApplication1.Models.CustomerOrderElectronicItem", b =>
                {
                    b.HasOne("WebApplication1.Models.ElectronicItem", "ElectronicItem")
                        .WithMany("CustomerOrderElectronicItems")
                        .HasForeignKey("E_ItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.CustomerOrder", "CustomerOrder")
                        .WithMany("CustomerOrderElectronicItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerOrder");

                    b.Navigation("ElectronicItem");
                });

            modelBuilder.Entity("WebApplication1.Models.ElectronicItem", b =>
                {
                    b.HasOne("WebApplication1.Models.Brand", "Brand")
                        .WithMany("ElectronicItems")
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Category", "Category")
                        .WithMany("ElectronicItems")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApplication1.Models.Employee", b =>
                {
                    b.HasOne("WebApplication1.Models.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("WebApplication1.Models.Employee", "UserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Models.BNPL_PLAN", b =>
                {
                    b.Navigation("BNPL_Installments");

                    b.Navigation("BNPL_PlanSettlementSummaries");
                });

            modelBuilder.Entity("WebApplication1.Models.BNPL_PlanType", b =>
                {
                    b.Navigation("BNPL_PLANs");
                });

            modelBuilder.Entity("WebApplication1.Models.Brand", b =>
                {
                    b.Navigation("ElectronicItems");
                });

            modelBuilder.Entity("WebApplication1.Models.Category", b =>
                {
                    b.Navigation("ElectronicItems");
                });

            modelBuilder.Entity("WebApplication1.Models.Customer", b =>
                {
                    b.Navigation("CustomerOrders");
                });

            modelBuilder.Entity("WebApplication1.Models.CustomerOrder", b =>
                {
                    b.Navigation("BNPL_PLAN");

                    b.Navigation("Cashflows");

                    b.Navigation("CustomerOrderElectronicItems");
                });

            modelBuilder.Entity("WebApplication1.Models.ElectronicItem", b =>
                {
                    b.Navigation("CustomerOrderElectronicItems");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
